apiVersion: apps/v1
kind: Deployment
metadata:
  name: assign3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assign3
  template:
    metadata:
      labels:
        app: assign3
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: assign3
        image: assign3acr.azurecr.io/spring-mvc-example:v1
        readinessProbe:
          httpGet:
            port: 8080
            path: /
        livenessProbe:
          httpGet:
            port: 8080
            path: /
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi      

---
apiVersion: v1
kind: Service
metadata:
  name: assign3-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
  - targetPort: 8080
  selector:
    app: assign3
