apiVersion: v1
kind: Service
metadata:
  name: assign3
  labels:
    app: assign3
spec:
  type: NodePort
  selector:
    app: assign3
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: assign3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: assign3
    spec:
      containers:
      - name: assign3
        image: acrassign2.azurecr.io/spring-mvc-example:v1
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1
